class QuestionStatus:
    CREATED = "CREATED"
    UNDER_ADMIN_REVIEW = "UNDER_ADMIN_REVIEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
